server:
  servlet-path: /app
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_manage?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: net.solooo.**.model
  mapperLocations: classpath:mapper/xml/*Mapper.xml

