package net.solooo.apimanage.mapper;

import java.util.List;
import net.solooo.apimanage.model.ApiInfo;
import net.solooo.apimanage.model.ApiInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ApiInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    long countByExample(ApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    int deleteByExample(ApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    int insert(ApiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    int insertSelective(ApiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    List<ApiInfo> selectByExample(ApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    ApiInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiInfo record, @Param("example") ApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiInfo record, @Param("example") ApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_api_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiInfo record);
}